//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FroneriATS.Module.BusinessObjects.FroneriATS
{

    public partial class asset_status : XPLiteObject
    {
        int fasset_status_id;
        [Key(true)]
        [MemberDesignTimeVisibility(false)]
        [DevExpress.Xpo.DisplayName(@"Oid")]
        public int asset_status_id
        {
            get { return fasset_status_id; }
            set { SetPropertyValue<int>(nameof(asset_status_id), ref fasset_status_id, value); }
        }
        string fasset_status_name;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Status name")]
        [DevExpress.Persistent.Validation.RuleRequiredField("asset_status_asset_status_name_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Enter Status Name")]
        public string asset_status_name
        {
            get { return fasset_status_name; }
            set { SetPropertyValue<string>(nameof(asset_status_name), ref fasset_status_name, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Assets")]
        [Association(@"assetReferencesasset_status")]
        public XPCollection<asset> assets { get { return GetCollection<asset>(nameof(assets)); } }
    }

}
