//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FroneriATS.Module.BusinessObjects.FroneriATS
{

    public partial class asset_person : XPLiteObject
    {
        int fasset_person_id;
        [Key(true)]
        [MemberDesignTimeVisibility(false)]
        [DevExpress.Xpo.DisplayName(@"Oid")]
        public int asset_person_id
        {
            get { return fasset_person_id; }
            set { SetPropertyValue<int>(nameof(asset_person_id), ref fasset_person_id, value); }
        }
        string fasset_person_name;
        [Indexed(Name = @"uni_name", Unique = true)]
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Person name")]
        [
DevExpress.Persistent.Validation.RuleRequiredField("asset_person_asset_person_name_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Enter Person Name")]
        public string asset_person_name
        {
            get { return fasset_person_name; }
            set { SetPropertyValue<string>(nameof(asset_person_name), ref fasset_person_name, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Assets")]
        [Association(@"assetReferencesasset_person")]
        public XPCollection<asset> assets { get { return GetCollection<asset>(nameof(assets)); } }
    }

}
