//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FroneriATS.Module.BusinessObjects.FroneriATS
{

    public partial class asset : XPLiteObject
    {
        int fasset_id;
        [Key(true)]
        [MemberDesignTimeVisibility(false)]
        [DevExpress.Xpo.DisplayName(@"Oid")]
        public int asset_id
        {
            get { return fasset_id; }
            set { SetPropertyValue<int>(nameof(asset_id), ref fasset_id, value); }
        }
        asset_type fasset_type_id;
        [Association(@"assetReferencesasset_type")]
        [DevExpress.Xpo.DisplayName(@"Asset type")]
        [DevExpress.Persistent.Validation.RuleRequiredField("asset_asset_type_name_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Enter Type Name")]
        public asset_type asset_type_id
        {
            get { return fasset_type_id; }
            set { SetPropertyValue<asset_type>(nameof(asset_type_id), ref fasset_type_id, value); }
        }
        asset_status fasset_status_id;
        [Association(@"assetReferencesasset_status")]
        [DevExpress.Xpo.DisplayName(@"Status")]
        [DevExpress.Persistent.Validation.RuleRequiredField("asset_asset_status_name_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Enter Status Name")]
        public asset_status asset_status_id
        {
            get { return fasset_status_id; }
            set { SetPropertyValue<asset_status>(nameof(asset_status_id), ref fasset_status_id, value); }
        }
        asset_model fasset_model_id;
        [Association(@"assetReferencesasset_model")]
        [DevExpress.Xpo.DisplayName(@"Model")]
        [DevExpress.Persistent.Validation.RuleRequiredField("asset_asset_model_name_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Enter Model Name")]
        public asset_model asset_model_id
        {
            get { return fasset_model_id; }
            set { SetPropertyValue<asset_model>(nameof(asset_model_id), ref fasset_model_id, value); }
        }
        DateTime fasset_register_date;
        [DevExpress.Xpo.DisplayName(@"Register date")]
        [DevExpress.Persistent.Validation.RuleRequiredField("asset_asset_register_date_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Enter Register date")]
        public DateTime asset_register_date
        {
            get { return fasset_register_date; }
            set { SetPropertyValue<DateTime>(nameof(asset_register_date), ref fasset_register_date, value); }
        }
        string fasset_number;
        [DevExpress.Xpo.DisplayName(@"Asset number")]
        [DevExpress.Persistent.Validation.RuleRequiredField("asset_asset_asset_number_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Enter Asset Number")]
        public string asset_number
        {
            get { return fasset_number; }
            set { SetPropertyValue<string>(nameof(asset_number), ref fasset_number, value); }
        }
        string fasset_serial_number;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Serial number")]
        [DevExpress.Persistent.Validation.RuleRequiredField("asset_serial_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Enter Serial Number")]
        public string asset_serial_number
        {
            get { return fasset_serial_number; }
            set { SetPropertyValue<string>(nameof(asset_serial_number), ref fasset_serial_number, value); }
        }
        asset_inventory fasset_inventory_id;
        [Association(@"assetReferencesasset_inventory")]
        [DevExpress.Xpo.DisplayName(@"Inventory")]
        [DevExpress.Persistent.Validation.RuleRequiredField("asset_asset_inventory_name_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Enter Inventory Name")]
        public asset_inventory asset_inventory_id
        {
            get { return fasset_inventory_id; }
            set { SetPropertyValue<asset_inventory>(nameof(asset_inventory_id), ref fasset_inventory_id, value); }
        }
        asset_person fasset_person_id;
        [Association(@"assetReferencesasset_person")]
        [DevExpress.Xpo.DisplayName(@"Person")]
        public asset_person asset_person_id
        {
            get { return fasset_person_id; }
            set { SetPropertyValue<asset_person>(nameof(asset_person_id), ref fasset_person_id, value); }
        }
        bool favailable;
        [DevExpress.Xpo.DisplayName(@"Available")]
        [DevExpress.Persistent.Validation.RuleRequiredField("asset_asset_available_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Enter Available")]
        public bool available
        {
            get { return favailable; }
            set { SetPropertyValue<bool>(nameof(available), ref favailable, value); }
        }
        string fnotes;
        [Size(1000)]
        [DevExpress.Xpo.DisplayName(@"Notes")]
        public string notes
        {
            get { return fnotes; }
            set { SetPropertyValue<string>(nameof(notes), ref fnotes, value); }
        }
    }

}
