//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FroneriATS.Module.BusinessObjects.FroneriATS
{

    public partial class asset_model : XPLiteObject
    {
        int fasset_model_id;
        [Key(true)]
        [MemberDesignTimeVisibility(false)]
        [DevExpress.Xpo.DisplayName(@"Oid")]
        public int asset_model_id
        {
            get { return fasset_model_id; }
            set { SetPropertyValue<int>(nameof(asset_model_id), ref fasset_model_id, value); }
        }
        string fasset_model_name;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Model name")]
        [DevExpress.Persistent.Validation.RuleRequiredField("asset_model_asset_model_name_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Enter Model Name")]
        public string asset_model_name
        {
            get { return fasset_model_name; }
            set { SetPropertyValue<string>(nameof(asset_model_name), ref fasset_model_name, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Assets")]
        [Association(@"assetReferencesasset_model")]
        public XPCollection<asset> assets { get { return GetCollection<asset>(nameof(assets)); } }
    }

}
