//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FroneriATS.Module.BusinessObjects.FroneriATS
{

    public partial class mobile_status : XPLiteObject
    {
        int fstatus_id;
        [Key(true)]
        [MemberDesignTimeVisibility(false)]
        [DevExpress.Xpo.DisplayName(@"Oid")]
        public int status_id
        {
            get { return fstatus_id; }
            set { SetPropertyValue<int>(nameof(status_id), ref fstatus_id, value); }
        }
        string fstatus_name;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Status")]
        [DevExpress.Persistent.Validation.RuleRequiredField("mobile_status_status_name_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "You must enter Status")]
        public string status_name
        {
            get { return fstatus_name; }
            set { SetPropertyValue<string>(nameof(status_name), ref fstatus_name, value); }
        }
        bool favailable_status;
        [DevExpress.Xpo.DisplayName(@"Available status")]
        public bool available_status
        {
            get { return favailable_status; }
            set { SetPropertyValue<bool>(nameof(available_status), ref favailable_status, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Mobiles")]
        [Association(@"mobileReferencesmobile_status")]
        public XPCollection<mobile> mobiles { get { return GetCollection<mobile>(nameof(mobiles)); } }
    }

}
