//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FroneriATS.Module.BusinessObjects.FroneriATS
{

    public partial class mobile_model : XPLiteObject
    {
        int fmodel_id;
        [Key(true)]
        [MemberDesignTimeVisibility(false)]
        [DevExpress.Xpo.DisplayName(@"Oid")]
        public int model_id
        {
            get { return fmodel_id; }
            set { SetPropertyValue<int>(nameof(model_id), ref fmodel_id, value); }
        }
        string fmodel_name;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Model")]
        [DevExpress.Persistent.Validation.RuleRequiredField("mobile_model_model_name_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "You must enter Model")]
        public string model_name
        {
            get { return fmodel_name; }
            set { SetPropertyValue<string>(nameof(model_name), ref fmodel_name, value); }
        }
        byte fserial_length;
        [DevExpress.Xpo.DisplayName(@"Serial length")]
        public byte serial_length
        {
            get { return fserial_length; }
            set { SetPropertyValue<byte>(nameof(serial_length), ref fserial_length, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Mobiles")]
        [Association(@"mobileReferencesmobile_model")]
        public XPCollection<mobile> mobiles { get { return GetCollection<mobile>(nameof(mobiles)); } }
    }

}
