//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FroneriATS.Module.BusinessObjects.FroneriATS
{

    public partial class printer_type : XPLiteObject
    {
        int fasset_type_id;
        [Key(true)]
        [MemberDesignTimeVisibility(false)]
        [DevExpress.Xpo.DisplayName(@"Oid")]
        public int asset_type_id
        {
            get { return fasset_type_id; }
            set { SetPropertyValue<int>(nameof(asset_type_id), ref fasset_type_id, value); }
        }
        string fasset_type_name;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Type name")]
        [DevExpress.Persistent.Validation.RuleRequiredField("printer_type_asset_type_name_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "You must enter Type name")]
        public string asset_type_name
        {
            get { return fasset_type_name; }
            set { SetPropertyValue<string>(nameof(asset_type_name), ref fasset_type_name, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Printers")]
        [Association(@"printerReferencesprinter_type")]
        public XPCollection<printer> printers { get { return GetCollection<printer>(nameof(printers)); } }
    }

}
