//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FroneriATS.Module.BusinessObjects.FroneriATS
{

    public partial class printer_model : XPLiteObject
    {
        int fasset_model_id;
        [Key(true)]
        [MemberDesignTimeVisibility(false)]
        [DevExpress.Xpo.DisplayName(@"Oid")]
        public int asset_model_id
        {
            get { return fasset_model_id; }
            set { SetPropertyValue<int>(nameof(asset_model_id), ref fasset_model_id, value); }
        }
        string fasset_model_name;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Model")]
        [DevExpress.Persistent.Validation.RuleRequiredField("printer_model_asset_model_name_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "You must enter Model")]
        public string asset_model_name
        {
            get { return fasset_model_name; }
            set { SetPropertyValue<string>(nameof(asset_model_name), ref fasset_model_name, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Printers")]
        [Association(@"printerReferencesprinter_model")]
        public XPCollection<printer> printers { get { return GetCollection<printer>(nameof(printers)); } }
    }

}
