//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FroneriATS.Module.BusinessObjects.FroneriATS
{

    public partial class user_inventory : XPLiteObject
    {
        int fuser_inventory_id;
        [Key(true)]
        [MemberDesignTimeVisibility(false)]
        [DevExpress.Xpo.DisplayName(@"Oid")]
        public int user_inventory_id
        {
            get { return fuser_inventory_id; }
            set { SetPropertyValue<int>(nameof(user_inventory_id), ref fuser_inventory_id, value); }
        }
        DevExpress.Persistent.BaseImpl.PermissionPolicy.PermissionPolicyUser fuser_id;
        [DevExpress.Xpo.DisplayName(@"User")]
        public DevExpress.Persistent.BaseImpl.PermissionPolicy.PermissionPolicyUser user_id
        {
            get { return fuser_id; }
            set { SetPropertyValue<DevExpress.Persistent.BaseImpl.PermissionPolicy.PermissionPolicyUser>(nameof(user_id), ref fuser_id, value); }
        }
        inventory fasset_inventory_id;
        [Association(@"user_inventoryReferencesinventory")]
        [DevExpress.Xpo.DisplayName(@"Inventory")]
        public inventory asset_inventory_id
        {
            get { return fasset_inventory_id; }
            set { SetPropertyValue<inventory>(nameof(asset_inventory_id), ref fasset_inventory_id, value); }
        }
    }

}
